name: Publish to PyPI
on:
  workflow_dispatch:
    inputs:
          version:
            description: 'version'
            required: true
jobs:
  pypi:
    if: ${{ inputs.pip}}
    runs-on: ubuntu-latest
    name: create pypi
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{inputs.version}}
      - name: Set up Python 3.11.4
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Build
        run: poetry build
      - name: Push to pypi
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish
